[set."org.gnome.desktop.wm.preferences"]
button-layout = "icon:maximize,close"

# nwg-look parameters -- if I understand correctly, it reads the config to
# preload in the UI from gsettings

[set."org.gnome.desktop.interface"]
gtk-theme = "Adwaita"
icon-theme = "Papirus"
font-name = "Noto Sans 10"
cursor-theme = "Vimix-white-cursors"
cursor-size = 24
toolbar-style = "both-horiz"
toolbar-icons-size = "large"
font-hinting = "slight"
font-antialiasing = "rgba"
font-rgba-order = "rgb"
text-scaling-factor = 1
color-scheme = "prefer-dark"
[set."org.gnome.desktop.sound"]
event-sounds = true
input-feedback-sounds = false
